<?php

$labels = array();
$labels['application_passwords'] = 'Hesla aplikací';

// Used in step 1 when creating new password
$labels['new_application_step1_legend'] = 'Krok 1 ze 2: Vygenerovat nové heslo pro aplikaci';
$labels['new_application_step1_description'] = 'Zadejte jméno, které vám pomůže zapamatovat si pro kterou je aplikaci (Pepovo Android, Thunderbird domácí PC).';
$labels['name'] = 'Jméno:';
$labels['create_password'] = 'Vygenerovat heslo';

// Used in step 2 when creating new password
$labels['new_application_step2_legend'] = 'Krok 2 ze 2: Zadejte vygenerované heslo';
$labels['new_application_step2_description'] = 'Nyní můžete zadat heslo ve vaší aplikaci. Upozorňujeme, že toto heslo poskytuje úplný přístup k vašemu e-mailovému účtu. Z bezpečnostních důvodů se již nebude zobrazovat. Použití mezer v hesle je volitelné.';

// Used in listing of existing passwords
$labels['existing_application_passwords'] = 'Vytvořená hesla';
$labels['applications'] = 'Aplikace';
$labels['date_created'] = 'Datum vytvoření';
$labels['date_last_used'] = 'Datum posledního přihlášení';
$labels['delete_warning'] = 'Upozornění! Smazáním hesla zabráníte aplikacím, které je používají, v přístupu k vaší poštovní schránce.';
?>